"""Generate the campaign screen atlas overlay from the code that owns each fact.

Three sources, none of which should be retyped by hand into a YAML file:

* `screen_regions` — where the persistent furniture is
* `ui_atlas`       — what each panel is and how to leave it
* `rome_shortcuts` — the game's own key bindings, read from the install

Hand-maintaining the overlay would guarantee drift the first time a coordinate is
re-measured, so it is generated instead:

    python scripts/build_campaign_atlas_overlay.py

Written to overlay/agent_skills/campaign_ui_atlas.yaml. Every value is a plain
str/int/float/bool/list/dict — the overlay is packed as JSON, and a bare ISO date
would deserialise to datetime.date and break session registration, so dates here
are quoted strings.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from comstar_game_ai.game_io.campaign import screen_regions, ui_atlas
from comstar_game_ai.game_io.campaign.rome_shortcuts import (
    camera_bindings,
    load_shortcuts,
)
from comstar_game_ai.game_io.campaign.rome_strings import load_campaign_tables

OUT = Path("overlay/agent_skills/campaign_ui_atlas.yaml")
VERIFIED_ON = "2026-09-05"

HEADER = """\
# GENERATED by scripts/build_campaign_atlas_overlay.py — do not edit by hand.
#
# Sources: screen_regions.py (geometry), ui_atlas.py (panel semantics),
# descr_shortcuts.txt and data/text/*.txt (the game's own bindings and names).
"""


def _regions() -> list[dict]:
    out = []
    for region in screen_regions.REGIONS:
        entry: dict = {
            "id": region.id,
            "kind": region.kind.value,
            "bounds": [round(v, 4) for v in region.bounds],
            "centre": list(region.centre),
            "purpose": " ".join(region.purpose.split()),
            "precision": region.precision.value,
        }
        if region.action:
            entry["action"] = region.action
        if region.note:
            entry["note"] = " ".join(region.note.split())
        out.append(entry)
    return out


def _panels(tables, db) -> list[dict]:
    out = []
    for entry in ui_atlas.ATLAS:
        panel: dict = {
            "id": entry.id,
            "name": entry.name(tables) if tables else None,
            "name_key": entry.name_key,
            "class": entry.panel_class.value,
            "blocking": entry.blocking,
            "expects_close_x": entry.expects_close_x,
            "dismiss": [d.value for d in entry.dismiss],
            "status": entry.status.value,
        }
        if entry.opened_by:
            panel["opened_by"] = entry.opened_by
        if entry.shortcut_action:
            panel["shortcut_action"] = entry.shortcut_action
            if db is not None:
                found = [b for b in db.find(entry.shortcut_action, keyset="moderntw") if b.chord]
                if found:
                    panel["shortcut"] = found[0].chord
        if entry.geometry is not None:
            geometry: dict = {
                "left": entry.geometry.left,
                "right": entry.geometry.right,
                "top": entry.geometry.top,
                "spans_centre": entry.geometry.spans_centre(),
            }
            if entry.geometry.close_x is not None:
                geometry["close_x"] = list(entry.geometry.close_x)
            panel["geometry"] = geometry
        if entry.note:
            panel["note"] = " ".join(entry.note.split())
        if entry.evidence:
            panel["evidence"] = list(entry.evidence)
        out.append(panel)
    return out


def _controls(db) -> dict:
    if db is None:
        return {"available": False, "reason": "descr_shortcuts.txt not found"}

    def chords(section: str, keyset: str) -> dict[str, str]:
        return {
            b.action: b.chord
            for b in db.bindings(keyset, section)
            if b.chord and not b.hidden
        }

    camera = {
        action: {
            "chord": binding.chord,
            "hold_to_repeat": binding.repeating,
            "section": binding.section,
        }
        for action, binding in camera_bindings(db, keyset="moderntw").items()
    }

    return {
        "available": True,
        "source": "data/text/descr_shortcuts.txt",
        "active_keyset": {
            "preference": "KEYSET:0 in preferences.txt",
            "assumed": "moderntw",
            "confirmed": False,
            "why_it_matters": (
                "The two keysets agree on end_turn (shift+enter) but disagree on the "
                "camera: moderntw zooms with Z/X, default zooms with Alt+Down/Alt+Up. "
                "Confirm by pressing Z on the campaign map and checking the zoom level "
                "before relying on any camera chord."
            ),
        },
        "camera": camera,
        "strat_map": chords("strat", "moderntw"),
        "keyset_default_camera": {
            action: binding.chord
            for action, binding in camera_bindings(db, keyset="default").items()
        },
    }


def main() -> int:
    tables = load_campaign_tables()
    db = load_shortcuts()

    doc = {
        "id": "campaign_ui_atlas",
        "description": (
            "Where each part of the Rome Remastered campaign screen is, what every "
            "panel is for, and the game's own key bindings for traversal and panels."
        ),
        "game": "Total War: ROME REMASTERED",
        "schema_version": 1,
        "generated_by": "scripts/build_campaign_atlas_overlay.py",
        "verified": VERIFIED_ON,
        "frame": {
            "coordinate_space": "client_rect_normalised",
            "measured_client_size": [1920, 1080],
            "aspect": "16:9",
            "warning": (
                "Capture the client rect, not the window rect. On the reference "
                "machine the window is 1936x1119 and the client 1920x1080; measuring "
                "against the window offsets every derived click."
            ),
        },
        "inject": {"heading": "## Campaign screen atlas", "max_chars": 6000},
        "how_to_use": [
            "Treat every coordinate as somewhere to look, not somewhere to click "
            "blindly. Only end_turn_button has been confirmed by an actuation.",
            "Prefer a key binding over a click when both exist: the bindings come "
            "from the game's own database and need no localisation.",
            "Prefer a radar click over held panning to cross distance.",
            "A blocking panel with no close X is a decision panel — read its footer "
            "instead of hunting for a dismiss button.",
        ],
        "regions": _regions(),
        "panels": _panels(tables, db),
        "controls": _controls(db),
        "coverage": {
            "panels_total": len(ui_atlas.ATLAS),
            "panels_verified": len(ui_atlas.verified()),
            "panels_unseen": [e.id for e in ui_atlas.unseen()],
            "regions_total": len(screen_regions.REGIONS),
            "regions_unverified": [r.id for r in screen_regions.unverified()],
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER)
        yaml.safe_dump(doc, handle, sort_keys=False, allow_unicode=True, width=100)

    print(f"wrote {OUT}")
    print(
        f"  {len(doc['regions'])} regions, {len(doc['panels'])} panels, "
        f"{len(doc['controls'].get('strat_map', {}))} strat bindings"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
